### ISSUE TITLE
grecaptcha.render is not a function

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [magento/magespecialist_ReCaptcha#10]
reCaptcha is not working on register page

### Preconditions

1. Magento 2.2.5
2. MSP_ReCaptcha latest composer version (currently 2.0.0)

### Steps to reproduce

1. Enable reCaptcha
2. Enable reCaptcha for register page
3. Go to register page on frontend

### Expected result
1. reCatpcha should.. work

### Actual result
1. reCaptcha is not working
2. In my browser developer console, i can see `grecaptcha.render is not a function`

### Simple fix
The fix is already existing on the repo: https://github.com/magento/magespecialist_ReCaptcha/commit/8d8c46458779dc66da39113c3e495394f7b98dfc

Please tag a new composer version for this fix to work on any composer installed Magento 2 instances.

**Comment by phoenix128** [comment]
Hello @Yonn-Trimoreau ,
we decided to fix in a slightly different way. A new release is available here: https://github.com/magento/magespecialist_ReCaptcha/releases/tag/v2.0.1 .
It will be soon available via composer.

**Comment by Yonn-Trimoreau** [comment]
Thank you :smiley:
