### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lang' of undefined

### ISSUE THREAD

**Issue by cyberkiller6** [magento/magespecialist_ReCaptcha#11]
I am receiving the following error on checkout page only, 

Uncaught TypeError: Cannot read property 'lang' of undefined

### Preconditions

1. Magento 2.2.5 Php 7.0 Mysql 5.6
2. Recaptcha version 2.0.0 installed through Magento
3. Porto theme 3.1.3 with aheadworks one step checkout 1.1.0
4. Multi stores, multi language store
5. Running in http mode

### Steps to reproduce

1. Add item to cart, proceed to checkout page

### Expected result

1. No type error and checkout work as normal

### Actual result

1. Uncaught TypeError: Cannot read property 'lang' of undefined
    at UiClass._loadApi (reCaptcha.js:69)
    at UiClass.initialize (reCaptcha.js:38)
    at UiClass.initialize (wrapper.js:109)
    at new UiClass (class.js:49)
    at Object.initComponent (layout.js:137)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at Object.deferred.(/us_en/checkout/anonymous function) (http://mydomain.com/pub/static/version1534662657/frontend/Smartwave/porto_child/en_US/jquery.js:3461:37)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)

**Comment by dccampbell** [comment]
Can confirm this issue, error occurs here: 
https://github.com/magento/magespecialist_ReCaptcha/blob/8280c2ae20c259cd6ecfd6ea6d1c07846998d381/view/frontend/web/js/reCaptcha.js#L69

Under certain conditions `this.settings` appears to be undefined at initialization. I believe I stopped seeing the error after changing some of the module settings in the admin and clearing cache.

While adding a `this.settings` check would resolve the error and allow `_loadApi()` to finish, I'm not sure if the settings would have loaded in afterwards or not. If the settings should always be available at that point, I feel like it'd make sense to bail out (with maybe a notice in the dev console) in scenarios where a) no settings are found, b) either of the keys are missing, or c) the module is set to disabled for the frontend.

**Comment by vivek79** [comment]
have anyone got the solution? I m facing the same issue in checkout with one step checkout extension.

**Comment by phoenix128** [comment]
This seems to be a theme related issue. Can you reproduce the same issue on a default template?

**Comment by garyconstable** [comment]
Im also having this issue after updating to the latest version of Mage 2, is there a fix ?

**Comment by AgentGod** [comment]
Same issue with clean install of magento 2.3.2

**Comment by Styopchik** [comment]
confirm on 2.3.2

**Comment by mtsmtyuta** [comment]
I've experienced the same issue on 2.3.2 today, and fixed it by updating Magefan_Blog from 2.8.0 to 2.8.10
So it can be an extension issue

**Comment by Styopchik** [comment]
@mtsmtyuta i have no such module, but have same issue

**Comment by AgentGod** [comment]
I have the issue on fresh&clean install of magento 2.3.2

**Comment by smoi** [comment]
I have the issue too on 2.3.2, any recommendations to fix it?

**Comment by Tarun-81** [comment]
Hello I have solved this issue. Please disable MSP_ReCaptcha module. Then its working fine.

**Comment by developeruserextension** [comment]
Hello, I have solved this issue. Please disable MSP_ReCaptcha module. Then its working fine.

**Comment by Styopchik** [comment]
@developeruserextension, I have beter solution - do not install magento at all)))

**Comment by creatifyteam** [comment]
temporary solution:
edit
MAGENTO_ROOT/vendor/msp/recaptcha/view/frontend/web/js/reCaptcha.js

line 69
to be
` element.src = 'https://www.google.com/recaptcha/api.js'
                    + '?onload=globalOnRecaptchaOnLoadCallback&render=explicit&hl=en; `

**Comment by sjonmx** [comment]
> Hello, I have solved this issue. Please disable MSP_ReCaptcha module. Then its working fine.

-bash-4.2$ php bin/magento module:disable MSP_ReCaptcha

Unable to change status of modules because of the following constraints:
Cannot disable MSP_ReCaptcha because modules depend on it:
Magento_PaypalReCaptcha: Magento_PaypalReCaptcha->MSP_ReCaptcha

**Comment by kanduvisla** [comment]
@sjonmx , you have to disable that module as well since it's a dependency:

```
php bin/magento module:disable Magento_PaypalReCaptcha
php bin/magento module:disable MSP_Recaptcha
```

Don't you think it's funny how every minor "patch" update of Magento always manages to include a lot of new modules, dependencies and issues?

**Comment by Rjgoolsby** [comment]
Ok, disabling modules is overkill and editing files in the vendor folder is bad because it will be overwritten the next time you run `composer update`. Do this instead. 

1. Create a custom Module. It's fairly easy. Here's instructions 
https://www.mageplaza.com/kb/how-create-hello-world-module-magento-2.html

2. Add a web js folder at this location 
`app/code/<VendorName>/<ModuleName>/view/frontend/web/js`
3. Create a require-config file here;
`app/code/<VendorName>/<ModuleName>/view/frontend/requirejs-config.js`

4. Copy the reCaptcha.js file from `vendor/msp/recaptcha/view/frontend/web/js/reCaptcha.js` to your `app/code/<VendorName>/<ModuleName>/view/frontend/web/js/reCaptcha.js` 

5. Add this to your requirejs-config.js
```  
var config = {
    map: {
       '*': {
            'MSP_ReCaptcha/js/reCaptcha': "VendorName_ModuleName>/js/reCaptcha", 
        }
    },
};

```
Run setup:upgrade, clean cache and carryon to the obvious soon to be next problem in Magento.

**Comment by jissereitsma** [comment]
@Rjgoolsby This is not needed in a separate module. You can also add this to a theme. Plus, this could be added using a mixin instead. Or even better, let's create a PR for this instead.

**Comment by jissereitsma** [comment]
See: https://github.com/magento/magespecialist_ReCaptcha/pull/47

**Comment by Rjgoolsby** [comment]
@jissereitsma Sounds good. I just realized I never showed my update to the file of reCaptcha.js. I saw your PR Request. I wonder if we should add the initial variable check. See my edited comment above. I feel it's always risky checking for properties of a variable that could potentially be undefined.

**Comment by jissereitsma** [comment]
Me too. So I would definitely recommend adding a separate PR for that variable check. Just editing the relevant file online here on GitHub will allow you to make a small PR like that.

**Comment by snoroozi** [comment]
same on 2.3.2 product pages

**Comment by gabriel3iri** [comment]
Confirmed, happening on 2.3.2 on product pages.

**Comment by phoenix128** [comment]
Hello @snoroozi and @gabriel3iri ,
plase upgrade to version 2.1.3.

**Comment by snoroozi** [comment]
Is it possible with core bundled extension?

**Comment by phoenix128** [comment]
I don't think you can upgrade through composer due to strict versioning requirement. I think using a patch is the fastest way.
As far as I know, this bugfix should be released together with the next minor Magento version.

**Comment by jissereitsma** [comment]
It might be that the official answer for bundled extensions would be to wait for the next bundle to be released (so Magento 2.3.3). However, you can also force an upgrade by adding the following `require` to your `composer.json`:
```bash
"msp/recaptcha": "2.1.3 as 2.1.2",
```
And then, run `composer update msp/recaptcha`. Should work.

**Comment by phoenix128** [comment]
@jissereitsma ,
yep, it could be an option

**Comment by Connexx** [comment]
I prefer the overwrite in my theme requirejs-config.js

**Comment by NikkyLauwers** [comment]
I prefer to fix this in my theme's requirejs-config.js. No need for an extra module...

**Comment by elfeffe** [comment]
> ```shell
> ```shell
> "msp/recaptcha": "2.1.3 as 2.1.2",
> ```
> ```

Then you get

    - magento/module-paypal-recaptcha 1.0.0 requires msp/recaptcha ^2.0.2 -> satisfiable by msp/recaptcha[2.1.2, 2.0.2] but these conflict with your requirements or minimum-stability.

**Comment by djbolya** [comment]
hey guys, here is , a module that was fixed this bug.
[MSPRecaptchaFixLang.zip](https://github.com/magento/magespecialist_ReCaptcha/files/3711302/MSPRecaptchaFixLang.zip)

just download and start smiling. 
:)

**Comment by chris-pook** [comment]
@elfeffe I believe this is now fixed in 2.3.3. I have just installed 2.3.3 and where I was seeing this issue on PDP in 2.3.2 I am now no longer seeing it.

**Comment by djbolya** [comment]
@elfeffe @chris-pook
Yes, the fix is next :
element.src = 'https://www.google.com/recaptcha/api.js'+ 'onload=globalOnRecaptchaOnLoadCallback&render=explicit' + (this.settings.lang ? '&hl=' + this.settings.lang : '');
This means that, if there aren't language code, they put empty string.
But I fixed it in another way, if there aren't language code, I just get it from current user browser. I think it is a better way.

**Comment by PoorlyRabbit** [comment]
Typo in earlier just-turn-the-module-off answer.

This worked for me:

` bin/magento module:disable  Magento_PaypalReCaptcha`
`bin/magento module:disable MSP_ReCaptcha`
`bin/magento cache:flush`
`bin/magento setup:upgrade`
`bin/magento setup:di:compile`
