### ISSUE TITLE
reCaptcha doesn't work property on Contact Page [Video]

### ISSUE THREAD

**Issue by mattkrupnik** [magento/magespecialist_ReCaptcha#13]
I am receiving the following error on Contact Page

*`Uncaught Error: reCAPTCHA placeholder element must be an element or id`*

### Preconditions

1. Magento 2.2.5 PHP 7.1
2. ReCaptcha version 2.0.1 installed through Magento
3. Luma Theme / Blank Theme

### Steps to reproduce

1. Go to `example.com/contact`
2. Remove from inspector some required field for example `<input name="name" id="name" title="Nazwa" value="" class="input-text" type="text" data-validate="{required:true}" aria-required="true">`
3. Fill all rest fields and check reCaptcha
4. Send message
5. You will get back error `Name is missing` - that's clear
6. In console you will see error `Uncaught Error: reCAPTCHA placeholder element must be an element or id`
7. Refresh page and reCaptcha doesn't show and in console will be error `Uncaught Error: reCAPTCHA placeholder element must be an element or id`
8. When I disable cache (layout, block_html, FPC) everything works fine or when I clean all site data then reCaptcha back after refresh

### Expected result

1. reCaptcha should be visible all the time
2. In console can't be any errors

### Actual result

1. https://youtu.be/mGLP4Y_NC7s

**Comment by phoenix128** [comment]
Hello @mattkrupnik ,
this was fixed in https://github.com/magento/magespecialist_ReCaptcha/pull/37 .
Thank you.
