### ISSUE TITLE
Cannot display 2 reCaptcha on one page

### ISSUE THREAD

**Issue by magefan** [magento/magespecialist_ReCaptcha#16]
If you use for e.g. popup for login, registration, forgot the password, and want to display the reCaptcha on both forms, only first recaptcha is displayed.

**Comment by phoenix128** [comment]
It should be already possible. An ID field is provided for such problems.
Have a look in one of the layout files.

Example:
**checkout_index_index.xml**
```
...
<item name="msp_recaptcha" xsi:type="array">
    ...
    <item name="reCaptchaId" xsi:type="string">msp-recaptcha-checkout-inline-login</item>
    <item name="zone" xsi:type="string">login</item>
    ...
</item>
...
```

Supposing you were using a custom template, did you check if it was correctly configured?

**Comment by Anrolosia** [comment]
Hello, I have the same issue there.

I want to add a captcha validation on footer newsletter subscribe, but when I go on a login page, or another one with a captcha validation, there is an issue with parameters in component.
It seems to take the second value and rewrite the first definition. For example, I have
`
<script type="text/x-magento-init">
--
  | {
  | "#msp-recaptcha-container": {
  | "Magento_Ui/js/core/app": {"components":{"msp-recaptcha":{"component":"MSP_ReCaptcha\/js\/reCaptcha","reCaptchaId":"msp-recaptcha-login","zone":"login","settings":{"siteKey":"xxxxxx","size":"invisible","badge":"bottomright ","theme":null,"lang":null,"enabled":{"login":true,"create":true,"forgot":true,"contact":true,"footer":true}}}}}    }
  | }
  | </script>
` and `<script type="text/x-magento-init">
--
  | {
  | "#msp-recaptcha-container": {
  | "Magento_Ui/js/core/app": {"components":{"msp-recaptcha":{"component":"MSP_ReCaptcha\/js\/reCaptcha","reCaptchaId":""msp-recaptcha-newsletter-footer","zone":"footer","settings":{"siteKey":"xxxxxx","size":"invisible","badge":"bottomright ","theme":null,"lang":null,"enabled":{"login":true,"create":true,"forgot":true,"contact":true,"footer":true}}}}}    }
  | }
  | </script>
`
but it seems to get reCaptchaId only from the second one. So it initialize the form login with the Captcha field id "msp-recaptcha-newsletter-footer" and so the second one can't be initialized...

Do you have a workaround please?

Thanks

**Comment by magefan** [comment]
@phoenix128, actually adding reCaptchaId item did not fixe the issue. We have debugged and prepared a solution: https://github.com/magefan/magespecialist_ReCaptcha/commit/e29291075eb609be670c1dd45edfb9f86de8da8e  . A main idea is to make scope and id attributes unic automaticaly.


Hope you can check and approve the merge request https://github.com/magento/magespecialist_ReCaptcha/pull/22 and release a new version as soon as it is posible.

@Anrolosia, can you confirm that our fix works for you too?

**Comment by Anrolosia** [comment]
@magefan Yeah, it fix the issue, thanks. I made a comment on your PR

Thanks

**Comment by phoenix128** [comment]
The proper support for the requested feature is avaialble here: https://github.com/magento/magespecialist_ReCaptcha/pull/27 .
