### ISSUE TITLE
magento 2 guest checkout doesn't show reCaptcha

### ISSUE THREAD

**Issue by wasimhc** [magento/magespecialist_ReCaptcha#31]
Preconditions (*)
1. Magento 2.2.7 & 2.3
2. MSP reCaptcha extension

Steps to reproduce (*)
- With MSP reCaptcha extension, Magento doesn't use reCaptcha in guest checkout. Though the reCaptcha is displayed if guest checkout is disabled or if checkout by registered customers.

Expected result (*)
- reCaptcha should be displayed in guest checkout.

Actual result (*)
- Guest can generate spam through checkout page.

**Comment by phoenix128** [comment]
Hello @wasimhc ,
IMO reCaptcha should not be used during a guest checkout procedure since no password is requested.
Adding to checkout could lead to a conversion rate decrease.

**Comment by wasimhc** [comment]
Hello @phoenix128 ,
Thank you for your message. That was a major requirement to impose reCaptcha in guest checkout. We've added this features 2 weeks ago in an alternative way.

**Comment by phoenix128** [comment]
If you like you can share it here and make it optional.
