### ISSUE TITLE
reCaptcha missing on Product Review & Newsletter Subscriber

### ISSUE THREAD

**Issue by matinict** [magento/magespecialist_ReCaptcha#36]
### Preconditions

1. Magento 2.3.1
2.  MSP reCaptcha version="1.5.0"

### Steps to reproduce

1. Need to Product Review Section
2. Need to  Newsletter Subscriber Section

### Expected result

1. show reCaptcha  Product Review & Newsletter Subscriber

### Actual result

1. [Screenshot, logs] Not Implemented yet

**Comment by phoenix128** [comment]
Requested feature were implemented in the following PRs:

- https://github.com/magento/magespecialist_ReCaptcha/pull/27
- https://github.com/magento/magespecialist_ReCaptcha/pull/18

**Comment by matinict** [comment]
@phoenix128 Thanks for quick update , its work properly for inviable reCaptcha
