### ISSUE TITLE
In the Admin panel the global search bar returns HTML tags to autocomplete results that are related to ReCaptcha

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_ReCaptcha#4]
### Preconditions:
ReCaptcha module is on

### Steps to reproduce:
Login to Admin
Set focus on global search bar
Type "rec"

### Expected result:
:white_check_mark: There are no HTML tags in the autocomplete

### Actual result:
:x: There are HTML tags in the autocomplete
![Screenshot](https://user-images.githubusercontent.com/11827230/35337596-54dd9920-0124-11e8-8659-e94cb44cd406.png)

**Comment by phoenix128** [comment]
Fixed on SecuritySuiteCommon package
