### ISSUE TITLE
Display "Inline" causes Badge to be displayed on ALL pages in bottom right aswell as inline

### ISSUE THREAD

**Issue by gwharton** [magento/magespecialist_ReCaptcha#42]
### Preconditions
1. Magento 2.2.8
2. MSP Recaptcha 2.1.2
3. Badge position set to inline

### Steps to reproduce
1. Go to homepage - No badge should be displayed
1. Go to contact us page - Badge should be displayed inline

### Expected result
1. No badge displayed on home page
2. Badge displayed inline only on contact us page

### Actual result
1. On homepage, infact, on EVERY page the badge is displayed in bottom right
2. On Captcha protected pages the Badge is shown inline, in addition to being displayed bottom right.

**Comment by gwharton** [comment]
Infact, even when set to bottom left, it appears in bottom right on most pages, even when no captcha form is present, i.e on category pages.

**Comment by gwharton** [comment]
Looks like it is the newsletter protection that is causing this as the recpatcha code is being included in the footer section. This is happening even though I have protection for newsletter disabled.

**Comment by phoenix128** [comment]
Hello @gwharton ,
I confirm the issue, we are fixing it.

**Comment by broopdias** [comment]
Hello, 
I'm having the exact same issue. 
Any fix already available?

**Comment by phoenix128** [comment]
Hello @gwharton and  @broopdias ,
the badge is displayed on every page because of the newsletter protection. Unfortunately, it cannot be displayed inline because it could break most of the custom themes. I think we should add this in the documentation.

**Comment by broopdias** [comment]
Hello,

We need newsletter protection enable, even we don't show the newsletter block, otherwise newsletter/subscriber/new/ route is reachabel by spam.

This issue descrived by happens when footer newsletter block is disabled on our theme
`<referenceBlock name="form.subscribe" remove="true"/>`

A simple solution is to enable this block, and hide it by css.

**Comment by vseager** [comment]
+1

**Comment by phoenix128** [comment]
Hello @broopdias ,
if you enable your credential to work with invisible recaptcha it should be working.
