### ISSUE TITLE
Admin ReCaptcha not compatible with Magento 2.1 due to escapeJs() usage

### ISSUE THREAD

**Issue by johnhughes1984** [magento/magespecialist_ReCaptcha#44]
### Preconditions
1. Magento Open Source / Commerce Edition 2.1.18
2. Admin ReCaptcha enabled and valid ReCaptcha keys set in config

### Steps to reproduce
1. Attempt to login in to admin panel

### Expected result
1. Login screen appears

### Actual result
1. Localized exception thrown: `Invalid method MSP\Recaptcha\Block\Adminhtml\ReCaptcha::escapeJs`

![Uploading screen_shot_2019-06-25_at_12.45.22.png…]()

### Issue
The `escapeJs()` method does not exist in Magento 2.1.x in `Magento\Framework\View\Element\AbstractBlock` hence the error.

It is also not present in `Magento\Framework\Escaper`, but does appear in `Magento\Framework\EscapeHelper` (which itself is not present in Magento 2.2.x / 2.3.x)

We've managed to patch this directly on our 2.1.x sites by switching to use `$this->helper(\Magento\Framework\EscapeHelper::class)` (not ideal, but we need a quick fix to get patches out).

However, given this doesn't exist in 2.2/2.3 as noted I'm not sure the best way this should be implemented to support all versions - I've never had to deal with DI where classes may or may not exist based on Magento version.

**Comment by phoenix128** [comment]
Hello @johnhughes1984 ,
starting from version 2.1.3, this module is not supposed to be compatible with Magento 2.1 or 2.0 .
