### ISSUE TITLE
Class 'ReCaptcha\\ReCaptcha' not found in app/code/MSP/ReCaptcha/Model/Validate.php:55

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_ReCaptcha#5]
**Steps to reproduce:**
Set Authy as 2FA for the admin that will try to pass the test
Tick in the checkbox to make it remember this device.

**Steps to reproduce:**
Configure Magento with credentials for reCAPTCHA V2
Enable for backend and storefront
On Storefront section choose type Invisible
Save configuration.
Log out
Log in ("I am not a robot" should be ticked)

**Expected result:**
I am redirected to the Dashboard

**Actual result:**
HTTP ERROR 500

[Fri Feb 16 16:43:23.926171 2018] [:error] [pid 22526] [client 10.234.128.66:58333] PHP Fatal error:  Uncaught Error: Class 'ReCaptcha\\ReCaptcha' not found in /var/www/html/tkhamlai/2fa/app/code/MSP/ReCaptcha/Model/Validate.php:55\nStack trace:\n#0 /var/www/html/tkhamlai/2fa/app/code/MSP/ReCaptcha/Observer/ReCaptchaObserver.php(93): MSP\\ReCaptcha\\Model\\Validate->validate('03AA7ASh1rQNWEo...', '10.234.128.66')\n#1 /var/www/html/tkhamlai/2fa/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(72): MSP\\ReCaptcha\\Observer\\ReCaptchaObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#2 /var/www/html/tkhamlai/2fa/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(60): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(MSP\\ReCaptcha\\Observer\\ReCaptchaObserver), Object(Magento\\Framework\\Event\\Observer))\n#3 /var/www/html/tkhamlai/2fa/lib/internal/Magento/Framework/Event/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#4 /var/www/html/tkhamlai/2fa/generated/code/Magento/Framework/Event/Manage in /var/www/html/tkhamlai/2fa/app/code/MSP/ReCaptcha/Model/Validate.php on line 55, referer: https://tsg.dev.magento.com/tkhamlai/2fa/admin/admin/index/index/key/f9535252fdb0de269e629c9bbefc7ba4a2c1542da6e08696c8d2fd86667182b6/

**Comment by phoenix128** [comment]
Hello @TomashKhamlai ,
this seems to be an issue related to your package composition. Are you sure you installed all the required dependencies? It seems you are missing `google/recaptcha` PHP package.

**Comment by TomashKhamlai** [comment]
Thank you. It helped.

**Comment by mahmoudissmail** [comment]
@phoenix128 Thank you. It helped.
