### ISSUE TITLE
Cannot add configurable product to cart

### ISSUE THREAD

**Issue by btarshad** [magento/magespecialist_ReCaptcha#50]
This is my url of configurable product:
http://essence.onlineprojectprogress.com/test-configure.html

When I try to add it to the cart it never added to the cart.

I am getting console error as well:
Uncaught TypeError: Cannot read property 'lang' of undefined in reCaptcha.js

I dont know if this issue is due to error or not.

**Comment by phoenix128** [comment]
Hello @btarshad ,
it does not seem to be related to reCaptcha.
To fix that warning please upgrade to the latest version.
