### ISSUE TITLE
Invisible reRecaptcha badge is shown on all pages even with type reCaptcha v2.(If Use in Newsletter = YES)

### ISSUE THREAD

**Issue by sdzhepa** [magento/magespecialist_ReCaptcha#53]
### Environment:
- Git based installation
- [Magento 2 Open Sorce](https://github.com/magento/magento2) `2.3-develop` branch on commit: 087939f59cd7eda6671d7330db806af710511ced
- [magespecialist_ReCaptcha](https://github.com/magento/magespecialist_ReCaptcha) `2.3-develop` branch on commit: 1a2170d165478c822b4cecbf65dcc745d8e6f46f

### Preconditions
- [Generate keys at Google](https://www.google.com/recaptcha/admin) Use ["I'm not a robot" Checkbox](https://www.screencast.com/t/mDhnR2NfvSf)
- SysConfig: Enable reCaptcha for Frontend
- SysConfig: reCaptcha type = *reCaptcha v2*
- SysConfig: **Use in Newsletter = YES**
- [Admin settings screen](https://www.screencast.com/t/k5IaiZhDZKf)

### Steps to reproduce

1. Go through several Storefront pages where reCaptcha should NOT be shown:
-- Home Page
-- Search Terms
-- Advanced Search
2. Go to any page where reCaptcha should be shown:
-- Sign In
-- Create an Account

### Expected result
- Invisible type reRecaptcha badge should NOT be shown if admin intentionally set reCaptcha type = *reCaptcha v2* (and requested exact keys only for "I'm not a robot" type)
- With this SysConfig setting should be shown only "I'm not a robot" and only on specified pages

### Actual result
- Invisible type reRecaptcha badge is snown on all pages(Home Page, Search Terms, etc) [Home Page Screen](https://www.screencast.com/t/iStzj8a9TxFI)
- Invisible type reRecaptcha badge has an error/warning message "This site key is not enabled for the invisible captcha."
- On pages like  Sign In/Create an Account are shown both types of reCaptca(Invisible and v2) [SignIn page screen](https://www.screencast.com/t/zXBvwCH6vv6)

### Additional Information
- It happens only with *Use in Newsletter = YES* setting.
- If set *Use in Newsletter = No*  Invisible type badge is not shown
-  Technically  this issue could be colled as a duplicate for https://github.com/magento/magespecialist_ReCaptcha/issues/45 but it has different Expected result and demonstrate several user flows and how it affects them

**Comment by phoenix128** [comment]
Hello @sdzhepa,
this is not an issue, but the expected behavior.
Newsletter reCaptcha can be only used with the invisible reCaptcha, so your API keys must support it. 

A configuration note will be added to avoid this kind of confusion.
