### ISSUE TITLE
There is no reCaptcha verification on "Newsletter Subscription" page even if emulate user agent = Googlebot/2.1.

### ISSUE THREAD

**Issue by sdzhepa** [magento/magespecialist_ReCaptcha#54]
### Environment:
- Git based installation
- [Magento 2 Open Sorce](https://github.com/magento/magento2) `2.3-develop` branch on commit: 087939f59cd7eda6671d7330db806af710511ced
- [magespecialist_ReCaptcha](https://github.com/magento/magespecialist_ReCaptcha) `2.3-develop` branch on commit: 1a2170d165478c822b4cecbf65dcc745d8e6f46f

### Preconditions
- [Generate keys at Google](https://www.google.com/recaptcha/admin) Use ["Invisible reCAPTCHA badge"](https://www.screencast.com/t/t8ASqKiGLSdC) type
- SysConfig: Enable reCaptcha for Frontend
- SysConfig: reCaptcha type = *Invisible reCaptcha*
- SysConfig: Use in Newsletter = YES
- SysConfig: Badge position = Bottom Left
- [Admin settings screen](https://www.screencast.com/t/4b7N18qosH)

### Steps to reproduce
1. Use Google Chrome browser (will be emulated like we are not a human but Googlebot, to have reCaptcha always fails, based on browser DevTools)
2. Go to Storefront and  Sign In as registered customer
3. Go to My Account > Newsletter Subscription
4. Enable "Googlebot emulation". The approach was found [here](https://stackoverflow.com/questions/43397678/is-it-possible-to-force-fail-a-recaptcha-v2-for-testing-purposes-i-e-pretend)
-- Open browser console
-- Click icon "Toggle device toolbar"
-- Add custom device with user agent = Googlebot/2.1.
-- [screen](https://www.screencast.com/t/J25FaDBbm)
5. Refresh the page to apply new test device setting
6. Select checkbox "General Subscription" = YES
7. Click Save button

### Expected result
- reCaptcha should fails validation and ask to "Select all images with.."
- reCaptcha Invisible badge should be shown "Bottom Left" position according to SysConfig from preconditions

### Actual result
- Customer Successfully subscribed
- reCaptcha does not show and ask to "Select all images with.."
-  reCaptcha Invisible badge is shown "Bottom Right" position

**Comment by itwebdev2** [comment]
I think this is related to the issue I logged #52 
GoogleBot User agent forces a spam score of 0.1 (the lowest you can have) and should definitely be marked as spam:
`object(ReCaptcha\Response)#2226 (7) { ["success":"ReCaptcha\Response":private]=> bool(true) ["errorCodes":"ReCaptcha\Response":private]=> array(0) { } ["hostname":"ReCaptcha\Response":private]=> string(17) "mag.diydirect.com" ["challengeTs":"ReCaptcha\Response":private]=> string(20) "2019-08-15T09:17:47Z" ["apkPackageName":"ReCaptcha\Response":private]=> NULL ["score":"ReCaptcha\Response":private]=> float(0.1) ["action":"ReCaptcha\Response":private]=> NULL }`
But as Google also returns "success" the module just assumes the submission was legitimate.

**Comment by phoenix128** [comment]
See my comments on #52
