### ISSUE TITLE
reCaptcha is added to all pages

### ISSUE THREAD

**Issue by BarryBadpak** [magento/magespecialist_ReCaptcha#58]
The invisible ReCaptcha ends up being displayed on all frontend pages within Magento 2, when looking at the console there is one javascript error within the reCaptcha.js file that shows up.

### Preconditions
1.  Magento 2.3.2

### Steps to reproduce
1. Install Magento 2.3.2
2. Configure MSP Recaptcha to use the Invisible reCaptcha

### Expected result
1. reCaptcha only shown on the pages as configured within the admin
2. No errors in the console

### Actual result
1. reCaptcha gets shown on all frontend pages
2. The following error isvisible within the console `Uncaught TypeError: Cannot read property 'nodeName' of undefined`

This exact issue is caused by `view/frontend/web/js/reCaptcha.js:161`, here `$parentForm[0]` gets passed into `$._data(...)` where it is trying to access properties on `undefined`. 

Line 150 makes it clear as to why it only happens when using the invisible recaptcha.

**Comment by kweij** [comment]
This is fixed in 2.1.3 and you can apply a patch for the meanwhile. I've explained it here: https://github.com/magento/magespecialist_ReCaptcha/issues/56#issuecomment-533145522

**Comment by bengower** [comment]
In Google Recaptcha set Use in newsletter to No. I haven't looked into what is causing it but this stops the error.

**Comment by bengower** [comment]
Modify line 150 in reCaptcha.js
from this:
if (this.settings.size === 'invisible') {

to this:
if (this.settings.size === 'invisible' && $parentForm.length > 0) {

The new line checks if a newsletter form is in the footer (or any matching form for that matter). I should mention that if you have a newsletter form in your footer you won't come across it. Hopefully it's the same issue you were experiencing.

**Comment by Wesdesignz** [comment]
We've implemented a patch into our list of default patches that fixes this issue, see the code below.
For us, this only presented a real issue for our customer that is still using Windows 7 / IE 11.

`From c938911a3bd6cc18f4958c4f333df559b1cf7fa7 Mon Sep 17 00:00:00 2001
From: Wesley Vestjens <wesley@getnoticed.nl>
Date: Tue, 22 Oct 2019 12:49:59 +0200
Subject: [PATCH] Implement a hotfix for a JavaScript issue occurring on
 Windows 7 / IE11 and lower

---
 vendor/msp/recaptcha/view/frontend/web/js/reCaptcha.js | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git a/vendor/msp/recaptcha/view/frontend/web/js/reCaptcha.js b/view/frontend/web/js/reCaptcha.js
index 29a8e48..1c7a6b0 100644
--- a/vendor/msp/recaptcha/view/frontend/web/js/reCaptcha.js
+++ b/vendor/msp/recaptcha/view/frontend/web/js/reCaptcha.js
@@ -130,6 +130,14 @@ define(
                 $reCaptcha.attr('id', this.getReCaptchaId());
 
                 $parentForm = $wrapper.parents('form');
+
+                /** FIX BY GET.NOTICED **/
+                /** Hotfix: if parentForm is not present, this code will break in W7/IE11 and lower. **/
+                if ($parentForm.length < 1) {
+                    return;
+                }
+                /** END FIX **/
+
                 me = this;
 
                 // eslint-disable-next-line no-undef
-- 
2.17.1

`

**Comment by phoenix128** [comment]
Hello @BarryBadpak ,
this is fixed in 2.2.2
