### ISSUE TITLE
Fatal error when login to admin or go to storefront. with new v3

### ISSUE THREAD

**Issue by sdzhepa** [magento/magespecialist_ReCaptcha#60]
### Preconditions

1.  Git based install of Magento 2 and reCaptcha
2. 

### Steps to reproduce

1.  Clone from git the latest Magento 2 code from `2.3-develop` branch
`git clone https://github.com/magento/magento2.git .`
2.  Clone from git the latest magespecialist_ReCaptcha code from `2.3-develop` branch and copy it into /magentoRootFolder/app/code/MSP/ReCaptcha
`git clone https://github.com/magento/magespecialist_ReCaptcha.git app/code/MSP/ReCaptcha`
3.  Add `google/recaptcha:^1.1` into composer
`composer require google/recaptcha:^1.1`
4. Install Magento
5. Go to Storefront
6. Go and login to the Admin

### Expected result

1.  (on step 5) Storefront: Homepage is opened
2.  (on step 6) Admin successfully logged in, admin dashboard page is opened 

### Actual result
1.  (on step 5) Storefront: blank page is opened
2.  (on step 6) after click Sign In button fatal error is shown
```
Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, null given in /var/www/magento/instance_1/app/code/MSP/ReCaptcha/Model/Config.php:97 Stack trace: #0 /var/www/magento/instance_1/app/code/MSP/ReCaptcha/Model/Config.php(97): trim(NULL) #1 /var/www/magento/instance_1/app/code/MSP/ReCaptcha/Model/Config.php(106): MSP\ReCaptcha\Model\Config->getPrivateKey() #2 /var/www/magento/instance_1/app/code/MSP/ReCaptcha/Model/IsCheckRequired.php(95): MSP\ReCaptcha\Model\Config->isEnabledBackend() #3 /var/www/magento/instance_1/app/code/MSP/ReCaptcha/Model/IsCheckRequired.php(124): MSP\ReCaptcha\Model\IsCheckRequired->isAreaEnabled() #4 /var/www/magento/instance_1/app/code/MSP/ReCaptcha/Observer/ReCaptchaObserver.php(86): MSP\ReCaptcha\Model\IsCheckRequired->execute() #5 /var/www/magento/instance_1/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(88): MSP\ReCaptcha\Observer\ReCaptchaObserver->execute(Object(Magento\Framework\Event\Observer)) #6 /var/www/magento/instance_1/lib/internal/Magento/Frame in /var/www/magento/instance_1/app/code/MSP/ReCaptcha/Model/Config.php on line 97
```

### Additional details
 after adding `declare(strict_types=1);` here https://github.com/magento/magespecialist_ReCaptcha/commit/1f6cfcd0ee175a6e322bfadb8a0571b687ed28d6#diff-b071d275e1d745730a8c09b2e009be6bR20

https://github.com/magento/magespecialist_ReCaptcha/blob/2.3-develop/Model/Config.php#L97 
**trim** receives NULL but expects string type

**Comment by phoenix128** [comment]
Hello @sdzhepa ,
thank you very much for your debug. This is fixed in 2.2.1 .
