### ISSUE TITLE
Fatal error if validation is skipped. Worked fine a few weeks ago

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_ReCaptcha#7]
**Preconditions:**
1. Google API website key is valid and authorized for my domain (type reCaptcha v2)
2. Google API secret key is valid and authorized for my domain (type reCaptcha v2)
3. reCaptcha is enabled for backend
4. reCaptcha is enabled for frontend
5. reCaptcha type for frontend is Invisible reCaptcha (the main idea is to set the valid keys but the wrong type of validation method)

**Steps to reproduce:**
1. Try to skip reCaptcha validation.
go to the **expected result** or do optional steps:
1. `rm -rf var/* generated/*`
2. `php bin/magento setup:upgrade`
3. `php bin/magento setup:static-content:deploy -f`
4. `php bin/magento cache:flush`
5. Press F12. On Application tab clear the site data and refresh the page. Try again to skip reCaptcha validation.

**Expected result:**
:white_check_mark: This site key is not enabled for the invisible captcha. ERROR for site owner: The registered key does not work with this interface.

**Actual result:**
:x: Fatal error in  `$this->failureProvider->execute($controller->getResponse());`:
`[Mon Feb 19 10:00:03.847638 2018] [:error] [pid 7980] [client 10.234.128.175:16410] PHP Fatal error:  Uncaught Error: Call to a member function getResponse() on null in /var/www/html/tkhamlai/2fa/app/code/MSP/ReCaptcha/Observer/ReCaptchaObserver.php:94\nStack trace:\n#0 /var/www/html/tkhamlai/2fa/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(72): MSP\\ReCaptcha\\Observer\\ReCaptchaObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#1 /var/www/html/tkhamlai/2fa/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(60): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(MSP\\ReCaptcha\\Observer\\ReCaptchaObserver), Object(Magento\\Framework\\Event\\Observer))\n#2 /var/www/html/tkhamlai/2fa/lib/internal/Magento/Framework/Event/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#3 /var/www/html/tkhamlai/2fa/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\\Framework\\Event\\Manager->dispatch('admin_user_auth...', Array)\n#4 /var/www/html/tkhamlai/2fa/app/code/Magento/User/Model in /var/www/html/tkhamlai/2fa/app/code/MSP/ReCaptcha/Observer/ReCaptchaObserver.php on line 94, referer: https://tsg.dev.magento.com/tkhamlai/2fa/admin/admin/index/index/key/24d20651bf6034eb8e2ed1f182e8ce877e55e47f12f93013c7d5032b309b74a1/`

**Comment by phoenix128** [comment]
Seems like you are still missing dependencies.

Please make sure you have all of the followings:

- "christian-riesen/base32": "^1.3",
- "spomky-labs/otphp": "~8.3",
- "endroid/qrcode": "~2.2",
- "donatj/phpuseragentparser": "~0.7",
- "yubico/u2flib-server": "^1.0"

**Comment by phoenix128** [comment]
Seems like you are using a version one week old. Is this the case?

**Comment by vkublytskyi** [comment]
@TomashKhamlai I also was not able to reproduce the issue on the latest code. If you still may reproduce it please provide more detailed STR otherwise please close it.

**Comment by TomashKhamlai** [comment]
Rechecked. It is not reproducible anymore.
